services:
  - type: web
    name: equity-ui
    runtime: docker
    dockerfilePath: Dockerfile.ui
    plan: free
    healthCheckPath: /
    envVars:
      - key: FMP_API_KEY
        sync: false
      - key: SEC_USER_AGENT
        sync: false
      # Leave OPENAI_API_KEY unset to disable Retriever/Citations gracefully
      - key: BASE_CURRENCY
        value: USD
      - key: EMBED_MODEL
        value: text-embedding-3-large
      - key: EMBED_DIM
        value: "3072"
