version: "3.8"
services:
  qdrant:
    image: qdrant/qdrant:v1.8.3
    ports: ["6333:6333"]
    volumes:
      - qdrant_storage:/qdrant/storage

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: example
    ports: ["5432:5432"]
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports: ["6379:6379"]

volumes:
  qdrant_storage:
  pg_data:

